### ISSUE TITLE
Connecting new (JUL’20) Wemo Smart Plugs (v4)

### ISSUE THREAD

**Issue by mgitz1313** [mozilla-iot/wemo-adapter#14]
I have two different versions of the Wemo smart plugs; mini, https://www.belkin.com/us/p/P-F7C063/, and the newest version, https://www.belkin.com/us/p/P-WSP080/ 1

The mini connected flawlessly. However, my gateway isn’t able to add or discover the new plugs. I’ve tried unplugging/re-plugging without success. In addition, I’ve rebooted gateway, network, etc.

**Comment by mrstegeman** [comment]
I just released a new version of the add-on. Please try it out and see if the new smart plug is supported.

**Comment by mgitz1313** [comment]
Thank you mrstegeman and I was able to connect plugs to the gateway a few minutes ago.
