### ISSUE TITLE
Things UI is not properly updated with manual interaction

### ISSUE THREAD

**Issue by trink** [mozilla-iot/wemo-adapter#2]
Wemo Insight Smart Plug: When the plug is manually turned on or off the state change is not reflected in the Things UI

**Comment by mrstegeman** [comment]
The devices are polled every 5 seconds or so. Is the UI updated after that?

**Comment by trink** [comment]
No, the only way to re-sync it is to click on the device in the gateway.

**Comment by mrstegeman** [comment]
Thanks for the bug report! Found the issue and posted a fix. I'll build a new release today, hopefully.
